config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contatos
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: %i[ show edit update destroy ]

  # GET /contatos or /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1 or /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos or /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: "Contato was successfully created." }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1 or /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: "Contato was successfully updated." }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1 or /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: "Contato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contato_params
      params.require(:contato).permit(:first_name, :last_name, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contatos/_form.html.erb
<%= form_with(model: contato) do |form| %>
  <% if contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
        <% contato.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone, class:"form-label" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <br>
  
  <div class="actions ">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form', contato: @contato %>
<br/>
<%= link_to 'Show', @contato, class:'btn btn-secondary' %> |
<%= link_to 'Back', contatos_path, class:'btn btn-secondary' %>

app/views/contatos/index.html.erb
<h1>Contatos</h1>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Sobrenome</th>
      <th scope="col">Email</th>
      <th scope="col">Telefone</th>
       <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
  <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.first_name %></td>
        <td><%= contato.last_name %></td>
        <td><%= contato.email %></td>
        <td><%= contato.phone %></td>
        <td>
          <%= link_to 'Show', contato, class:"btn btn-secondary fa-thin fa-eye" %>
          <%= link_to 'Edit', edit_contato_path(contato), class:"btn btn-secondary fa-thin fa-edit"  %>
          <%= link_to 'Destroy', contato, class:"btn btn-danger fa-thin fa-trash" , method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contato', new_contato_path, class:"btn btn-secondary" %>

app/views/contatos/new.html.erb
<h1>New Contato</h1>
    <br/>
  <div class="actions ">
    <%= render 'form', contato: @contato, class:'btn btn-secondary' %>
    <br/>
    <%= link_to 'Back', contatos_path, class:'btn btn-secondary' %>

  </div>

app/views/contatos/show.html.erb
<div class="bg-light p-5 rounded-lg m-3">
  <h1 class="display-4"> <%= @contato.first_name %>  <%= @contato.last_name %></h1>

  <p>
    <strong>Email:</strong>
    <%= @contato.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @contato.phone %>
  </p>

  <%= link_to 'Edit', edit_contato_path(@contato), class:"btn btn-secondary"  %> |
  <%= link_to 'Back', contatos_path, class:"btn btn-dark"  %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
    <%= link_to 'Agenda App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Contatos', contatos_path, class:"nav-link" %>
        </li>

        

        <li class="nav-item">
          <%= link_to 'About', home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to 'Add Contato', new_contato_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
            </li>
          <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About!</h1>
This is About Page

app/views/home/index.html.erb
<h1>Hello World!</h1>
 This is my first Rails webpage

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous">
    <title>Agenda Rails</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
      
      <div class="container">
        <!-- Content here -->
        <br/>
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>

        <%= yield %>
      </div>
    
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>